name: Hello World

on:
  push:
      branches: [ action_test ]
      
jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Greetings
        run: |
          echo "Current working directory: $GITHUB_WORKSPACE"
          echo "Hello World!"
