name: Hello World

on:
  push:
      branches: [ action_test ]

env:
  TITLE: "GitHub.Action Test"
  AUTHOR: "Binh"

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: action_test

      - name: Create artifacts folder
        run: mkdir -p artifacts

      - name: Create sample file
        run: |
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Datetime: $CURRENT_TIME" > artifacts/datetime.txt
          echo "Saved: $CURRENT_TIME"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: artifacts
          retention-days: 7
