name: Hello World

on:
  push:
      branches: [ action_test ]

env:
  TITLE: "GitHub.Action Test"
  AUTHOR: "Binh"

jobs:
  make-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: action_test

      - name: Create artifacts folder
        run: mkdir -p artifacts

      - name: Create sample file
        run: |
          CURRENT_TIME=$(date +"%Y-%m-%d %H:%M:%S")
          echo "Datetime: $CURRENT_TIME" > artifacts/datetime.txt
          echo "Saved: $CURRENT_TIME"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: datetime-file
          path: artifacts
          retention-days: 7

  read-file:
    runs-on: ubuntu-latest
    needs: make-file
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: datetime-file
          path: artifacts
          
      - name: Read datetime from file
        run: |
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/artifacts
          DATETIME=$(cat artifacts/datetime.txt)
          echo "The saved datetime is: $DATETIME"
          echo "DATETIME=$DATETIME" >> $GITHUB_ENV
